title: Hong's site
description: >- # this means to ignore newlines until "baseurl:"
# todo
baseurl: ""
url: ""

permalink: /blog/:title/

plugins:
  - jekyll-feed

encoding: UTF-8

sass:
  sass_dir: assets/css

# defaults:
#   - 
#     scope:
#       path: 
#       type: posts 
#     values:
#         layout: post
